// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ergmCntNLPL_cpp
double ergmCntNLPL_cpp(NumericVector coef, List obj, int rtype, NumericVector rparam);
RcppExport SEXP _btergm_ergmCntNLPL_cpp(SEXP coefSEXP, SEXP objSEXP, SEXP rtypeSEXP, SEXP rparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type rtype(rtypeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rparam(rparamSEXP);
    rcpp_result_gen = Rcpp::wrap(ergmCntNLPL_cpp(coef, obj, rtype, rparam));
    return rcpp_result_gen;
END_RCPP
}
// ergmCntNLPLDeriv_cpp
List ergmCntNLPLDeriv_cpp(NumericVector coef, List obj, int rtype, NumericVector rparam);
RcppExport SEXP _btergm_ergmCntNLPLDeriv_cpp(SEXP coefSEXP, SEXP objSEXP, SEXP rtypeSEXP, SEXP rparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type rtype(rtypeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rparam(rparamSEXP);
    rcpp_result_gen = Rcpp::wrap(ergmCntNLPLDeriv_cpp(coef, obj, rtype, rparam));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_btergm_ergmCntNLPL_cpp", (DL_FUNC) &_btergm_ergmCntNLPL_cpp, 4},
    {"_btergm_ergmCntNLPLDeriv_cpp", (DL_FUNC) &_btergm_ergmCntNLPLDeriv_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_btergm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
